package ru.avg.server.model.topic;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import ru.avg.server.model.meeting.Meeting;

/**
 * Entity representing a topic discussed in a meeting.
 * This class maps to the 'topic' database table and represents an agenda item or discussion point
 * within a specific meeting context.
 * <p>
 * The Topic entity establishes a many-to-one relationship with the Meeting entity, meaning each topic
 * belongs to exactly one meeting, while a meeting can have multiple topics. This relationship is
 * enforced through the 'meeting_id' foreign key constraint in the database.
 * </p>
 * <p>
 * Key attributes include:
 * <ul>
 *   <li>{@code id}: Auto-generated unique identifier for the topic</li>
 *   <li>{@code title}: Descriptive name or subject of the discussion point</li>
 *   <li>{@code meeting}: Reference to the parent meeting to which this topic belongs</li>
 * </ul>
 * </p>
 * <p>
 * The entity uses Lombok annotations to reduce boilerplate code:
 * <ul>
 *   <li>{@link Data} - generates getters, setters, equals, hashCode, and toString methods</li>
 *   <li>{@link Builder} - provides a fluent API for object construction</li>
 *   <li>{@link NoArgsConstructor} - generates a no-arguments constructor</li>
 *   <li>{@link AllArgsConstructor} - generates a constructor with all fields</li>
 * </ul>
 * </p>
 *
 * @see Meeting
 * @see Entity
 * @see Table
 * @author AVG
 * @since 1.0
 */
@Entity
@Table(name = "topic")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Topic {

    /**
     * Unique identifier for the topic.
     * This field is auto-generated by the database using the IDENTITY strategy.
     * It serves as the primary key for the 'topic' table and cannot be null or modified after creation.
     *
     * @see GenerationType#IDENTITY
     * @see Id
     * @see Column#name()
     * @see Column#nullable()
     * @see Column#updatable()
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Integer id;

    /**
     * Title or subject of the topic.
     * This field represents the main agenda item or discussion point for a meeting.
     * It is stored in the 'title' database column and cannot be null, ensuring every
     * topic has a descriptive name.
     * <p>
     * The title is typically displayed in meeting agendas and minutes to identify
     * what will be discussed or was discussed during the meeting.
     * </p>
     *
     * @see Column#name()
     * @see Column#nullable()
     */
    @Column(name = "title", nullable = false)
    private String title;

    /**
     * Reference to the parent meeting to which this topic belongs.
     * This field establishes a many-to-one relationship with the Meeting entity,
     * where multiple topics can belong to a single meeting.
     * <p>
     * The relationship is mapped to the 'meeting_id' column in the 'topic' table,
     * which acts as a foreign key referencing the primary key of the 'meeting' table.
     * The field cannot be null, ensuring referential integrity by requiring every
     * topic to be associated with a valid meeting.
     * </p>
     *
     * @see ManyToOne
     * @see JoinColumn#name()
     * @see JoinColumn#nullable()
     * @see Meeting
     */
    @ManyToOne
    @JoinColumn(name = "meeting_id", nullable = false)
    private Meeting meeting;
}