package ru.avg.server.model.company;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Entity representing a company in the system.
 * Maps to the 'company' database table.
 *
 * <p>This class serves as a JPA entity that models a company with essential corporate attributes
 * such as name, tax identification number (INN), company type, and governance structure.
 * It is used for persistence operations through Spring Data JPA and is typically converted
 * to DTOs ({@link ru.avg.server.model.dto.company.CompanyDto}) for external exposure.</p>
 *
 * <p>Key attributes:
 * <ul>
 *   <li>{@code id}: Auto-generated unique identifier assigned by the database.</li>
 *   <li>{@code title}: Official business name of the company; must not be null.</li>
 *   <li>{@code inn}: Individual Taxpayer Number (INN) — a 10-digit tax identification number;
 *       must be unique across all companies.</li>
 *   <li>{@code companyType}: Classification of the company (e.g., LLC, JSC) stored as an
 *       enum value in the database using string representation.</li>
 *   <li>{@code hasBoardOfDirectors}: Boolean flag indicating whether the company has
 *       a board of directors as part of its governance model; cannot be null.</li>
 * </ul>
 * </p>
 *
 * <p>The entity uses Lombok annotations to reduce boilerplate code:
 * <ul>
 *   <li>{@link Data} generates getters, setters, {@code toString()}, {@code equals()}, and {@code hashCode()}.</li>
 *   <li>{@link Builder} enables fluent object construction.</li>
 *   <li>{@link NoArgsConstructor} generates a no-argument constructor needed for JPA.</li>
 *   <li>{@link AllArgsConstructor} generates a constructor with all fields.</li>
 * </ul>
 * </p>
 *
 * @see ru.avg.server.model.dto.company.CompanyDto for the corresponding data transfer object
 * @see CompanyType for the enum defining possible company classifications
 * @author AVG
 * @since 1.0
 */
@Entity
@Table(name = "company")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Company {

    /**
     * Unique identifier for the company, auto-generated by the database.
     * This field serves as the primary key and is immutable once set.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Integer id;

    /**
     * Official name or title of the company.
     * Must not be null and is stored in the database as a non-nullable field.
     */
    @Column(name = "title", nullable = false)
    private String title;

    /**
     * Individual Taxpayer Number (INN) — a 10-digit tax identification number
     * assigned to the company. Must be unique across all records in the system.
     */
    @Column(name = "inn", nullable = false, unique = true)
    private Long inn;

    /**
     * Type of the company (e.g., LLC, JSC) represented as an enum.
     * Stored in the database as a string value corresponding to the enum constant.
     * Cannot be null.
     */
    @Column(name = "company_type", nullable = false)
    @Enumerated(EnumType.STRING)
    private CompanyType companyType;

    /**
     * Indicates whether the company has a board of directors.
     * Used in corporate governance logic; must be explicitly set to true or false.
     * Cannot be null.
     */
    @Column(name = "has_board_of_directors", nullable = false)
    private Boolean hasBoardOfDirectors;
}