package ru.avg.server.model.voting;

import lombok.Getter;

/**
 * Enumeration of possible vote options in a voting process.
 * Each vote type has a corresponding Russian title for display purposes.
 * <p>
 * This enum defines the complete set of voting choices available in the system:
 * <ul>
 *   <li>{@link #NOT_VOTED} - Participant did not cast a vote</li>
 *   <li>{@link #YES} - Participant voted in favor of the proposal</li>
 *   <li>{@link #NO} - Participant voted against the proposal</li>
 *   <li>{@link #ABSTAINED} - Participant attended but chose not to vote</li>
 * </ul>
 * </p>
 * <p>
 * The enum is used in {@link ru.avg.server.model.voting.Voter} to record the voting decisions
 * of participants during meeting topics. The Russian titles are used for display in user interfaces
 * and official documents generated by the system.
 * </p>
 *
 * @see ru.avg.server.model.voting.Voter
 * @see ru.avg.server.model.voting.Voting
 * @author AVG
 * @since 1.0
 */
@Getter
public enum VoteType {

    /**
     * Represents a participant who did not cast a vote.
     * This status is assigned when a participant is present at the meeting but does
     * not submit a voting decision for a particular topic.
     * Display title in Russian: "НЕ ГОЛОСОВАЛ".
     */
    NOT_VOTED("НЕ ГОЛОСОВАЛ"),

    /**
     * Represents a vote in favor of the proposal.
     * This status indicates the participant supports the agenda item being voted on.
     * Display title in Russian: "ЗА".
     */
    YES("ЗА"),

    /**
     * Represents a vote against the proposal.
     * This status indicates the participant opposes the agenda item being voted on.
     * Display title in Russian: "ПРОТИВ".
     */
    NO("ПРОТИВ"),

    /**
     * Represents a participant who abstained from voting.
     * This status indicates the participant was present but chose not to vote,
     * often due to conflict of interest or other reasons.
     * Display title in Russian: "ВОЗДЕРЖАЛСЯ".
     */
    ABSTAINED("ВОЗДЕРЖАЛСЯ");

    /**
     * The Russian-language title of the vote type, used for display in the user interface
     * and official documents. Each vote type has a corresponding human-readable title
     * in Russian to support the system's localization requirements.
     *
     * @see #getTitle()
     */
    private final String title;

    /**
     * Constructs a new VoteType with the specified display title.
     *
     * @param title the Russian title of the vote type; must not be null
     * @throws NullPointerException if title is null
     */
    VoteType(String title) {
        this.title = title;
    }
}