package ru.avg.server.model.voting;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import ru.avg.server.model.participant.MeetingParticipant;
import ru.avg.server.model.topic.Topic;

/**
 * Entity representing a voter in a voting process within a meeting.
 * This class maps to the 'voter' database table and captures the vote cast by a meeting participant
 * on a specific topic, including the vote type and whether it involves a related-party transaction.
 * <p>
 * The Voter entity establishes relationships with three key entities:
 * <ul>
 *   <li>{@link Voting} - the parent voting process to which this vote belongs</li>
 *   <li>{@link MeetingParticipant} - the participant who cast the vote</li>
 *   <li>{@link Topic} - the agenda item being voted on</li>
 * </ul>
 * </p>
 * <p>
 * The entity enforces referential integrity through foreign key constraints and ensures that:
 * <ul>
 *   <li>Each vote has a unique identifier generated by the database</li>
 *   <li>The voting, participant, and topic associations are mandatory</li>
 *   <li>The vote type is stored as a string representation of the enum</li>
 *   <li>The related-party transaction status is explicitly recorded</li>
 * </ul>
 * </p>
 *
 * @see Voting
 * @see MeetingParticipant
 * @see Topic
 * @see VoteType
 * @author AVG
 * @since 1.0
 */
@Entity
@Table(name = "voter")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Voter {

    /**
     * Unique identifier for the voter record.
     * This field is auto-generated by the database using the IDENTITY strategy.
     * It serves as the primary key for the 'voter' table and cannot be null or modified after creation.
     *
     * @see GenerationType#IDENTITY
     * @see Id
     * @see Column#name()
     * @see Column#nullable()
     * @see Column#updatable()
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Integer id;

    /**
     * Reference to the parent voting process to which this vote belongs.
     * Establishes a many-to-one relationship with the Voting entity.
     * Maps to 'voting_id' column in the database and is mandatory (cannot be null).
     * Uses lazy fetching to optimize performance, loading the voting data only when accessed.
     * <p>
     * This field represents the owning side of the relationship, where the
     * voter table contains a foreign key to the voting table.
     * </p>
     *
     * @see Voting
     * @see ManyToOne
     * @see FetchType#LAZY
     * @see JoinColumn#name()
     * @see JoinColumn#nullable()
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "voting_id", nullable = false)
    private Voting voting;

    /**
     * Reference to the meeting participant who cast this vote.
     * Establishes a many-to-one relationship with the MeetingParticipant entity.
     * Maps to 'meeting_participant_id' column in the database and is mandatory (cannot be null).
     * Uses lazy fetching to optimize performance, loading the participant data only when accessed.
     * <p>
     * This field links the vote to the specific participant in the meeting,
     * maintaining the connection between the voting process and attendance.
     * </p>
     *
     * @see MeetingParticipant
     * @see ManyToOne
     * @see FetchType#LAZY
     * @see JoinColumn#name()
     * @see JoinColumn#nullable()
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "meeting_participant_id", nullable = false)
    private MeetingParticipant participant;

    /**
     * Reference to the topic that is the subject of this vote.
     * Establishes a many-to-one relationship with the Topic entity.
     * Maps to 'topic_id' column in the database and is mandatory (cannot be null).
     * Uses lazy fetching to optimize performance, loading the topic data only when accessed.
     * <p>
     * This field ensures that each vote is associated with a valid agenda item
     * from the meeting, maintaining the context of what is being voted on.
     * </p>
     *
     * @see Topic
     * @see ManyToOne
     * @see FetchType#LAZY
     * @see JoinColumn#name()
     * @see JoinColumn#nullable()
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "topic_id", nullable = false)
    private Topic topic;

    /**
     * The type of vote cast by the participant.
     * Represents the participant's position on the topic, such as FOR, AGAINST, ABSTAIN, or NON_VOTING.
     * Stored in the 'vote' database column as a string value using {@link EnumType#STRING} mapping.
     * <p>
     * This field captures the actual voting choice made by the participant
     * during the voting process and is used in calculating voting results.
     * </p>
     *
     * @see VoteType
     * @see Column#name()
     * @see Enumerated
     * @see EnumType#STRING
     */
    @Column(name = "vote")
    @Enumerated(EnumType.STRING)
    private VoteType vote;

    /**
     * Indicates whether this vote involves a related-party transaction.
     * Stored in the 'is_related_party_deal' database column as a boolean value.
     * <p>
     * This field is used to identify votes that may have conflicts of interest
     * or require additional disclosure according to corporate governance rules.
     * It helps in generating proper reporting for regulatory compliance.
     * </p>
     */
    @Column(name = "is_related_party_deal")
    private boolean isRelatedPartyDeal;
}