package ru.avg.server.model.voting;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import ru.avg.server.model.topic.Topic;

import java.util.List;

/**
 * Entity representing a voting session conducted on a meeting topic.
 * This class maps to the 'voting' database table and captures the complete voting process
 * for a specific agenda item, including the final outcome and individual votes.
 * <p>
 * The Voting entity establishes a one-to-many relationship with the Voter entity,
 * meaning each voting session can have multiple votes from different participants,
 * while each vote belongs to exactly one voting session. It also maintains a many-to-one
 * relationship with the Topic entity, linking the voting process to a specific agenda item.
 * </p>
 * <p>
 * Key attributes include:
 * <ul>
 *   <li>{@code id}: Auto-generated unique identifier for the voting session</li>
 *   <li>{@code topic}: Reference to the topic being voted on (mandatory)</li>
 *   <li>{@code isAccepted}: Final outcome of the vote (true = accepted, false = rejected)</li>
 *   <li>{@code voters}: List of participants who cast votes in this session</li>
 * </ul>
 * </p>
 * <p>
 * The entity uses Lombok annotations to reduce boilerplate code:
 * <ul>
 *   <li>{@link Data} - generates getters, setters, equals, hashCode, and toString methods</li>
 *   <li>{@link Builder} - provides a fluent API for object construction</li>
 *   <li>{@link NoArgsConstructor} - generates a no-arguments constructor</li>
 *   <li>{@link AllArgsConstructor} - generates a constructor with all fields</li>
 * </ul>
 * </p>
 *
 * @author AVG
 * @see Topic
 * @see Voter
 * @see Entity
 * @see Table
 * @since 1.0
 */
@Entity
@Table(name = "voting")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Voting {

    /**
     * Unique identifier for the voting session.
     * This field is auto-generated by the database using the IDENTITY strategy.
     * It serves as the primary key for the 'voting' table and cannot be null or modified after creation.
     *
     * @see GenerationType#IDENTITY
     * @see Id
     * @see Column#name()
     * @see Column#nullable()
     * @see Column#updatable()
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Integer id;

    /**
     * Reference to the topic being voted on in this session.
     * Establishes a many-to-one relationship with the Topic entity.
     * Maps to 'topic_id' column in the database and is mandatory (cannot be null).
     * Uses lazy fetching to optimize performance, loading the topic data only when accessed.
     * <p>
     * This field represents the owning side of the relationship, where the
     * voting table contains a foreign key to the topic table.
     * </p>
     *
     * @see Topic
     * @see ManyToOne
     * @see FetchType#LAZY
     * @see JoinColumn#name()
     * @see JoinColumn#nullable()
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "topic_id", nullable = false)
    private Topic topic;

    /**
     * The final outcome of the voting session.
     * Represents whether the proposal was accepted (true) or rejected (false) based on voting results.
     * Stored in the 'is_accepted' database column as a boolean value and is mandatory (cannot be null).
     * <p>
     * This field is determined by the voting rules and quorum requirements after all votes
     * have been collected and counted. It serves as the official record of the decision made.
     * </p>
     */
    @Column(name = "is_accepted", nullable = false)
    private boolean isAccepted;

    /**
     * List of voters who participated in this voting session.
     * Establishes a one-to-many relationship with the Voter entity.
     * Mapped by the 'voting' field in the Voter entity and uses lazy loading for performance.
     * Any changes to voters are cascaded to the database, and orphaned voters are automatically removed.
     * <p>
     * This collection contains all individual votes cast during the session, including
     * the participant, their vote choice, and related-party transaction status.
     * Lazy fetching prevents loading all voter data when only voting metadata is needed.
     * </p>
     *
     * @see Voter
     * @see OneToMany
     * @see FetchType#LAZY
     * @see CascadeType#ALL
     * @see #isAccepted
     */
    @OneToMany(mappedBy = "voting", fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Voter> voters;

    /**
     * Returns a string representation of the Voting entity, including key attributes.
     * This implementation provides a concise view of the voting session, showing the ID,
     * topic reference, acceptance status, and number of voters (if any).
     * <p>
     * The string format is: "Voting{id=..., topic=..., isAccepted=..., votersCount=...}"
     * This method overrides the default toString() generated by Lombok's @Data annotation
     * to provide a more meaningful representation that avoids potential infinite recursion
     * when topics or voters have their own toString() methods that reference this entity.
     * </p>
     *
     * @return a string representation of the Voting entity with key attributes
     */
    @Override
    public String toString() {
        return "Voting{" +
                "id=" + id +
                ", topic=" + topic +
                ", isAccepted=" + isAccepted +
                ", votersCount=" + (voters != null ? voters.size() : 0) +
                '}';
    }
}