package ru.avg.server.model.participant;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import ru.avg.server.model.company.Company;

/**
 * Entity representing a participant in a company, such as a shareholder, founder, or board member.
 * Maps to the 'participant' database table.
 * <p>
 * This class serves as a JPA entity that models an individual or legal entity involved in a company's governance
 * and ownership structure. It is commonly used to represent stakeholders who participate in meetings,
 * hold shares, and have defined roles within the organization.
 * </p>
 * <p>
 * Key attributes:
 * <ul>
 *   <li>{@code id}: Auto-generated unique identifier assigned by the database.</li>
 *   <li>{@code name}: Full name of the participant; cannot be null and is stored as a non-nullable field.</li>
 *   <li>{@code share}: Numerical value representing the ownership percentage or shareholding;
 *       stored with precision and must not be null.</li>
 *   <li>{@code company}: Reference to the {@link Company} to which this participant belongs;
 *       enforced as non-null to maintain referential integrity.</li>
 *   <li>{@code type}: Classification of the participant (e.g., OWNER, MEMBER_OF_BOARD) stored
 *       as a string representation of the {@link ParticipantType} enum; cannot be null.</li>
 *   <li>{@code isActive}: Boolean flag indicating whether the participant is currently active
 *       in the company’s operations; cannot be null.</li>
 * </ul>
 * </p>
 * <p>
 * The entity uses Lombok annotations to reduce boilerplate code:
 * <ul>
 *   <li>{@link Data} generates getters, setters, {@code toString()}, {@code equals()}, and {@code hashCode()}.</li>
 *   <li>{@link Builder} enables fluent object construction.</li>
 *   <li>{@link NoArgsConstructor} generates a no-argument constructor needed for JPA.</li>
 *   <li>{@link AllArgsConstructor} generates a constructor with all fields.</li>
 * </ul>
 * </p>
 *
 * @author AVG
 * @see Company for the parent company relationship
 * @see ParticipantType for the enum defining possible participant classifications
 * @since 1.0
 */
@Entity
@Table(name = "participant")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Participant {

    /**
     * Unique identifier for the participant, auto-generated by the database.
     * This field serves as the primary key and is immutable once set.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Integer id;

    /**
     * Full name of the participant.
     * Must not be null and is stored in the database as a non-nullable field.
     */
    @Column(name = "name", nullable = false)
    private String name;

    /**
     * Ownership share or percentage held by the participant in the company.
     * Stored with a precision of 5 digits; cannot be null.
     */
    @Column(name = "share", nullable = false, precision = 5)
    private Double share;

    /**
     * Reference to the company to which this participant belongs.
     * Establishes a many-to-one relationship with the {@link Company} entity.
     * Cannot be null — every participant must be associated with a company.
     */
    @ManyToOne
    @JoinColumn(name = "company_id", nullable = false)
    private Company company;

    /**
     * Type or classification of the participant (e.g., OWNER, MEMBER_OF_BOARD).
     * Stored in the database as a string representation of the {@link ParticipantType} enum.
     * Must not be null.
     */
    @Column(name = "type", nullable = false)
    @Enumerated(EnumType.STRING)
    private ParticipantType type;

    /**
     * Indicates whether the participant is currently active in the company.
     * Used to manage participant lifecycle; cannot be null.
     */
    @Column(name = "is_active", nullable = false)
    private Boolean isActive;
}