package ru.avg.server.model.meeting;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import ru.avg.server.model.company.Company;
import ru.avg.server.model.participant.Participant;

import java.time.LocalDate;

/**
 * Entity representing a meeting within the system.
 * Maps to the 'meeting' database table.
 * <p>
 * This class serves as a JPA entity that models a corporate meeting with essential attributes
 * such as type, date, location, and key participants. It establishes relationships with
 * the {@link Company} organizing the meeting and {@link Participant} entities assigned
 * to specific roles (chairman and secretary).
 * </p>
 * <p>
 * Key fields include:
 * <ul>
 *   <li>{@code id}: Auto-generated unique identifier assigned by the database.</li>
 *   <li>{@code company}: Reference to the {@link Company} that owns/organizes this meeting;
 *       enforced as non-null to ensure every meeting belongs to a company.</li>
 *   <li>{@code type}: Classification of the meeting (e.g., Annual, Extraordinary) stored
 *       as an enum using string representation in the database.</li>
 *   <li>{@code date}: The scheduled date of the meeting; cannot be null.</li>
 *   <li>{@code address}: Physical location where the meeting will take place; limited to 512 characters
 *       and required for logistical tracking.</li>
 *   <li>{@code secretary} and {@code chairman}: Optional references to {@link Participant}
 *       entities who hold official roles in the meeting. These may be null if not yet assigned.</li>
 * </ul>
 * </p>
 * <p>
 * The entity uses Lombok annotations to reduce boilerplate code:
 * <ul>
 *   <li>{@link Data} generates getters, setters, {@code toString()}, {@code equals()}, and {@code hashCode()}.</li>
 *   <li>{@link Builder} enables fluent object construction.</li>
 *   <li>{@link NoArgsConstructor} generates a no-argument constructor needed for JPA.</li>
 *   <li>{@link AllArgsConstructor} generates a constructor with all fields.</li>
 * </ul>
 * </p>
 *
 * @author AVG
 * @see MeetingType for the enum defining possible meeting classifications
 * @see Company for the parent company relationship
 * @see Participant for the participant role assignments
 * @since 1.0
 */
@Entity
@Table(name = "meeting")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Meeting {

    /**
     * Unique identifier for the meeting, auto-generated by the database.
     * This field serves as the primary key and is immutable once set.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, updatable = false)
    private Integer id;

    /**
     * Reference to the company that organizes this meeting.
     * Establishes a many-to-one relationship with the {@link Company} entity.
     * Cannot be null — every meeting must belong to a company.
     */
    @ManyToOne
    @JoinColumn(name = "company_id", nullable = false)
    private Company company;

    /**
     * Type or classification of the meeting (e.g., Annual General Meeting, Extraordinary Meeting).
     * Stored in the database as a string representation of the {@link MeetingType} enum.
     * Must not be null.
     */
    @Column(name = "type", nullable = false)
    @Enumerated(EnumType.STRING)
    private MeetingType type;

    /**
     * The date on which the meeting is scheduled to occur.
     * Cannot be null — every meeting must have a defined date.
     */
    @Column(name = "date", nullable = false)
    private LocalDate date;

    /**
     * Physical address or location where the meeting will be held.
     * Limited to 512 characters for database consistency.
     * Cannot be null — a location must be specified for all meetings.
     */
    @Column(name = "address", nullable = false, length = 512)
    private String address;

    /**
     * Participant assigned to the role of secretary for this meeting.
     * The secretary is responsible for recording minutes and official documentation.
     * This field may be null if the role has not yet been assigned.
     */
    @ManyToOne
    @JoinColumn(name = "secretary_id")
    private Participant secretary;

    /**
     * Participant assigned to the role of chairman for this meeting.
     * The chairman presides over the meeting and ensures procedural compliance.
     * This field may be null if the role has not yet been assigned.
     */
    @ManyToOne
    @JoinColumn(name = "chairman_id")
    private Participant chairman;
}